### ISSUE TITLE
Fix server table to use the correct cursor type

### ISSUE THREAD

**Issue by Southclaws** [Southclaws/samp-servers-frontend#1]
The caret cursor is wrong and it should be a hand pointer instead.

Gotta figure out Semantic UI theming for this I guess...

https://github.com/Semantic-Org/Semantic-UI/issues/3533
https://gist.github.com/thejohnfreeman/563337119e20d090ea2d22bee9b05a6b

**Comment by Ino-Bagaric** [comment]
Could you just download it (css) on your local edit it and import in html, i think for now that is simplest way

```css
table tbody {
    cursor: pointer;
}
```

**Comment by Southclaws** [comment]
That's the plan, I had a play with the Semantic UI full package but couldn't seem to get it to build properly, I'll give it another go tomorrow as I'm probably just doing something wrong with gulp and webpack...

**Comment by Southclaws** [comment]
alright screw the semantic theming, did it in the html...
