### ISSUE TITLE
Error 400 on adding server

### ISSUE THREAD

**Issue by AmirSavand** [Southclaws/samp-servers-frontend#10]
I tried to add a server that's already in and I got endless loading...

Here's the technical info:

#### Request

```
Request URL: https://api.samp-servers.net/v2/server
Request Method: POST
Status Code: 400 
Payload: 95.213.255.83:7771
```

#### Response

```
no address specifiedrequest address '172.30.0.5' does not match declared server address ''
```

#### Screenshot

![image](https://user-images.githubusercontent.com/4629328/45285843-3725a000-b4f5-11e8-9670-783fc39f4732.png)

**Comment by Southclaws** [comment]
This is resolved now due to changes to the backend.
