### ISSUE TITLE
How many people use this website?

### ISSUE THREAD

**Issue by AmirSavand** [Southclaws/samp-servers-frontend#9]
Is there stats you can show?

BTW Loving the service!

**Comment by Southclaws** [comment]
I've actually never got around to installing Google Analytics so unfortunately, I have no idea how many people use it.

I'm glad you like it though!

**Comment by AmirSavand** [comment]
Alright I guess you can close this issue.

Yes you've done quite the work for SA-MP. If this project was Angular I'd explode it with pull requests.
